# -*- coding: utf-8 -*-
"""pythonfile(BonusTask1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xCR1eTgaY67-PMXGEWs3H10J7QtPRYN9
"""

!pip install rdflib
!pip install SPARQLWrapper

import csv
import pandas as pd
from rdflib import Graph, Literal, Namespace, RDF, RDFS, URIRef

# Read the CSV file using pandas
csv_file = "query.csv"
df = pd.read_csv(csv_file)

# Load the existing ontology from a file
g = Graph()
g.parse("Ontology.ttl", format="turtle")

# Define your ontology namespace
ns = Namespace("http://www.semanticweb.org/satyamsharma/ontologies/HigherEducation/")

# Get references to the existing classes and properties in the ontology
UniversityClass = ns.University
CountryClass = ns.Country
CityClass = ns.City
LocatedInProp = ns.locatedIn
CountryLocatedProp = ns.countryLocated
FoundedProp = ns.founded
NumberOfStudentsProp = ns.numberOfStudents

# Iterate through the CSV rows and add them to the ontology
for _, row in df.iterrows():
    university_uri = URIRef(row["university"])
    university_label = Literal(row["universityLabel"])
    year_founded = Literal(row["yearFounded"])
    total_students = Literal(row["totalStudents"])

    # Add the university entity and its properties
    g.add((university_uri, RDF.type, UniversityClass))
    g.add((university_uri, RDFS.label, university_label))
    g.add((university_uri, FoundedProp, year_founded))
    g.add((university_uri, NumberOfStudentsProp, total_students))
    

# Serialize and save the ontology to a file
with open("Updated_ontology.ttl", "w") as output_file:
    output_file.write(g.serialize(format="turtle"))

print("Ontology successfully updated with CSV data!")