# -*- coding: utf-8 -*-
"""pythonfile (4).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1trw5pnzfwE8GOas2v6StG_inlIFaBoRa
"""

!pip install rdflib
!pip install SPARQLWrapper

from rdflib import Graph, Namespace
from SPARQLWrapper import SPARQLWrapper, RDF

# Load the original ontology
original_ontology_path = "file.ttl"
g = Graph()
g.parse(original_ontology_path, format="turtle")

# Define the SPARQL endpoint and query
sparql_endpoint = "https://dbpedia.org/sparql"
sparql_query = """
PREFIX hist: <http://www.semanticweb.org/satyamsharma/ontologies/HigherEducation/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema/>

CONSTRUCT {
    ?uni rdf:type hist:University .
    ?uni hist:countryLocated ?country .
    ?country rdf:type hist:country .
    ?uni hist:hasPresident ?president .
    ?president rdf:type hist:president.
    ?president hist:presidentName ?presidentName .
    ?uni hist:locatedIn ?city .
    ?city rdf:type hist:city .  
    ?uni hist:numberOfStudents ?numberOfStudents .
    ?uni hist:founded ?established .
    ?uni hist:motto ?motto .
}
WHERE {
    ?uni rdf:type dbo:University .
    ?uni dbp:name ?name .
    OPTIONAL { ?uni dbo:country ?country . }
    OPTIONAL { ?uni dbo:city ?city . }
    OPTIONAL { ?uni dbp:president ?presidentName . 
               BIND(BNODE() AS ?president) }
    OPTIONAL { ?uni dbo:numberOfStudents ?numberOfStudents . }
    OPTIONAL { ?uni dbp:established ?established . }
    OPTIONAL { ?uni dbo:motto ?motto . }
    OPTIONAL { ?uni dbo:website ?website . }

    FILTER regex(str(?name), "American InterContinental University|Baresan University|Bay Path University|Baylor University|Beal University|Beijing University of Technology|Belhaven University|Benguet State University|Bethel University (Indiana)|Bicol University|Canadian University Dubai|Cape Breton University|Capitol Technology University|Cardinal Stritch University|Campbell University|Caldwell University|Sam Houston State University|Rowan University|Roosevelt University|Rogers State University")
}
"""
# Execute the SPARQL query
sparql = SPARQLWrapper(sparql_endpoint)
sparql.setQuery(sparql_query)
sparql.setReturnFormat(RDF)
results = sparql.query().convert()

# Merge the results into the original graph
g += results

# Save the updated graph to a new file
new_ontology_path = "Ontology.ttl"
g.serialize(destination=new_ontology_path, format="turtle")
print("Ontology populated and saved to Ontology.ttl")